// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZJg8rFLeT0zG8-LZxMIV6ruY2XzJNpbA',
    appId: '1:726125712404:web:8f5f76de3c9de5b17b8301',
    messagingSenderId: '726125712404',
    projectId: 'authflutter-23a28',
    authDomain: 'authflutter-23a28.firebaseapp.com',
    storageBucket: 'authflutter-23a28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAULuNDg7bRdGBERS8MyBs_JU6rcGY5ZGg',
    appId: '1:726125712404:android:c2a97c5af5bfced57b8301',
    messagingSenderId: '726125712404',
    projectId: 'authflutter-23a28',
    storageBucket: 'authflutter-23a28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLKEdNTFA7Hm6IBBaXKyQPh66mNwC-D3Q',
    appId: '1:726125712404:ios:8e77e701433645bc7b8301',
    messagingSenderId: '726125712404',
    projectId: 'authflutter-23a28',
    storageBucket: 'authflutter-23a28.appspot.com',
    iosClientId: '726125712404-4ujrf06kibq0miinv2edirh001q5fu3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp2',
  );
}
